set nocompatible

syntax on

set ttimeoutlen=50

set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
augroup END

set ruler
set numberwidth=5

set tabstop=2
set shiftwidth=2
set smarttab
set expandtab

set laststatus=2
set ignorecase
set cursorline
set wildmenu

set splitbelow
set splitright

nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

" let &t_SI = "\<ESC>[6 q"
" let &t_SR = "\<ESC>[4 q"
" let &t_EI = "\<ESC>[2 q"

call plug#begin('~/.vim/plugged')
  Plug 'ryanoasis/vim-devicons'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'ajh17/Spacegray.vim'
  Plug 'vim-scripts/bufexplorer.zip'
  Plug 'HerringtonDarkholme/yats'
  Plug 'Quramy/tsuquyomi'
  Plug 'Valloric/YouCompleteMe'
  Plug 'craigemery/vim-autotag'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
"  Plug 'tpope/vim-surround'
"  Plug 'SirVer/ultisnips'
  Plug 'airblade/vim-gitgutter'
"  Plug 'mattn/emmet-vim'
  Plug 'tpope/vim-vinegar'
  Plug 'mhinz/vim-startify'
call plug#end()

if (has("termguicolors"))
  set termguicolors
endif

colorscheme spacegray

let g:airline_powerline_fonts=1
let g:airline_solarized_bg='dark'
let g:airline_theme='solarized'
let g:airline#extensions#tabline#enabled=1

highlight Comment cterm=italic gui=italic

if !exists("g:ycm_semantic_triggers")
  let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers['typescript'] = ['.']

let g:tsuquyomi_disable_quickfix = 1
let g:tsuquyomi_use_vimproc = 0
"autocmd InsertLeave,TextChanged,BufWritePost *.ts,*.tsx call tsuquyomi#asyncGeterr()
autocmd BufWritePost *.ts,*.tsx call tsuquyomi#asyncGeterr()

nnoremap <C-p> :FZF<CR>
nnoremap <C-o> :Explore<CR>

"let g:ctrlp_map = '<C-p>'
"let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
"augroup fzf
"  autocmd!
"  autocmd! FileType fzf
"  autocmd  FileType fzf set laststatus=0 noshowmode noruler
"        \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
"augroup END

if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

