version = 2
final_space = true
console_title_template = ' {{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    background = 'blue'
    foreground = 'black'
    # template = '{{.Icon}} '
    template = '{{.Icon}} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ .Path }}'
    background = 'black'
    # foreground = 'white'
    foreground = 'blue'

    [blocks.segments.properties]
      style = 'agnoster_full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}white{{ end }}', '{{ if gt .Ahead 0 }}white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}orange{{ end }}', '{{ if gt .Behind 0 }}magenta{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'green'
    foreground = 'black'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = [
      '{{ if gt .Code 0 }}red{{ end }}'
    ]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    background = 'blue'
    foreground = 'black'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # leading_diamond = ''
    # trailing_diamond = ''
    foreground = 'white'
    background = 'black'

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    template = '   {{.Full}}  <b>{{.Venv}}</b> '
    background = 'yellow'
    foreground = 'black'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    template = '  {{.Full}} '
    background = 'green'
    foreground = 'black'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = true
      home_enabled = false

  [[blocks.segments]]
    type = 'angular'
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    template = '  {{.Full}} '
    background = 'red'
    foreground = 'black'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      home_enabled = false

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    leading_diamond = ''
    trailing_diamond = ''
    template = ' <b>{{ .CurrentDate | date "15:04:05" }}</b>'
    background = 'blue'
    foreground = 'black'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{ if gt .Code 0 }}red{{ end }}'
    ]
    foreground = 'green'
    background = 'transparent'
    template = "❯"

[transient_prompt]
  background = 'transparent'
  foreground = 'white'
  template = "❯ "

[[tooltips]]
  type = "aws"
  tips = [ "aws", "a" ]
  style = "plain"
  foreground = "#e0af68"
  template = "f {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[tooltips]]
  type = "git"
  tips = [ "git", "g" ]
  style = "diamond"
  foreground = "#193549"
  background = "#fffb38"
  leading_diamond = ""
  trailing_diamond = ""
  template = "{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}"

    [tooltips.properties]
    fetch_status = true
    fetch_upstream_icon = true
